# Generated by Django 5.2.7 on 2025-11-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genero',
            name='icono',
            field=models.ImageField(blank=True, null=True, upload_to='generos_iconos/'),
        ),
    ]
